//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solvek.Gears.Engine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solvek.Gears.Engine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process expects {0} input{1} but {2} were provided..
        /// </summary>
        internal static string Errors_Process_InputsAmount {
            get {
                return ResourceManager.GetString("Errors_Process_InputsAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process does not allow any inputs. But {0} input(s) provided..
        /// </summary>
        internal static string Errors_Process_NoInputAllowed {
            get {
                return ResourceManager.GetString("Errors_Process_NoInputAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process expected agument of type {0}.
        /// </summary>
        internal static string Errors_Process_WrongType {
            get {
                return ResourceManager.GetString("Errors_Process_WrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}th argument expected of type {1}.
        /// </summary>
        internal static string Errors_Process_WrongTypeN {
            get {
                return ResourceManager.GetString("Errors_Process_WrongTypeN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка.
        /// </summary>
        internal static string WidgetStatus_Failed {
            get {
                return ResourceManager.GetString("WidgetStatus_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Немає даних.
        /// </summary>
        internal static string WidgetStatus_NotUpdated {
            get {
                return ResourceManager.GetString("WidgetStatus_NotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гаразд.
        /// </summary>
        internal static string WidgetStatus_Success {
            get {
                return ResourceManager.GetString("WidgetStatus_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оновлення.
        /// </summary>
        internal static string WidgetStatus_Updating {
            get {
                return ResourceManager.GetString("WidgetStatus_Updating", resourceCulture);
            }
        }
    }
}
